### ISSUE TITLE
1.12.2 Port?

### ISSUE THREAD

**Issue by vizthex123** [SilentChaos512/SuperMultiDrills#23]
## Versions
1.12.2

## What Should Be Added or Changed?
Port the mod to 1.12.2 please.

## Why Should This Be Done?
It lets me use one of my favourite mods.

**Comment by SilentChaos512** [comment]
I don't support old versions. I don't have enough time as it is.

Porting this mod would be especially time-consuming considering the huge Silent Lib changes after 1.11. And backporting the 1.15+ version would be impossible because Silent Gear is nowhere near as developed in that version. If someone wants to take on the task of porting the 1.11 version, they are welcome to do so.

**Comment by vizthex123** [comment]
Man....alright then.
